### ISSUE TITLE
Clean Up / Transform The Database

### ISSUE THREAD

**Issue by AldaronLau** [libcala/stick#13]
In the TOML files in `./pad_db/pad/mapping`, it looks like
```toml
name = "Joystick Name"
type = "Unknown"

[[button]]
code = 2
event = "ActionA"

[[button]]
code = 0
# ...
```

# Tasks
 - [ ] Names should be consistent PS, PlayStation, Playstation, Play Station => PlayStation; GC, GameCube, Gamecube, Game Cube => GameCube
 - [ ] Types should not be "UNKNOWN", except for xxxxxxxxxxxxxxxx.toml, they should be things like `FLIGHT`, `GAMECUBE`, `NES`, `XBOX`, `WII`
 - [ ] Types should be all caps, no underscores, spaces or any other separators
 - [x] Button entries should be sorted by `code`, smallest to largest
 - [x] Axes entries should be sorted by `code`, smallest to largest
 - [x] Three-way entries should be sorted by `code`, smallest to largest
 - [x] Trigger entries should be sorted by `code`, smallest to largest

~Some of these tasks may be done using scripts, but I will only include the scripts in the repository if it's written in Rust or Python.  Other tasks will need to be done manually.~  There is now a script in Rust in the repository.  The remaining tasks don't need a script.

**Comment by AldaronLau** [comment]
Fixed.
